{"uuid": "f67ad884-3c15-4196-b448-a88bfaa7883a", "children": ["a8ba2c26-23d3-489f-bc0a-8d76dcd97d4d"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost/addressbook/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost.\nStacktrace:\nWebDriverError@chrome://marionette/content/error.js:175:5\nUnknownError@chrome://marionette/content/error.js:482:5\nhandleReadyState@chrome://marionette/content/listener.js:297:13\nhandleEvent@chrome://marionette/content/listener.js:263:14\n\n", "trace": "  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\conftest.py\", line 29, in app\n    fixture.session.ensure_login(username=web_config['username'], password=web_config['password'])\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\fixture\\session.py\", line 49, in ensure_login\n    self.login(username, password)\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\fixture\\session.py\", line 8, in login\n    self.app.open_home_page()\n  File \"C:\\Users\\ASinelnikova\\PycharmProjects\\python_training\\fixture\\application.py\", line 36, in open_home_page\n    wd.get(\"http://localhost/addressbook/\")\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 350, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 338, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\asinelnikova\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1584644072723, "stop": 1584644074785}], "start": 1584644072723, "stop": 1584644074834}